# Generated by Django 6.0.3 on 2026-03-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.CharField(blank=True, help_text='e.g. Rwf450M', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.IntegerField(default=0, help_text='Percentage 0-100'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('on-track', 'On Track'), ('at-risk', 'At Risk'), ('delayed', 'Delayed'), ('completed', 'Completed')], default='on-track', max_length=50),
        ),
    ]
