# Generated by Django 6.0.3 on 2026-03-22 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_budget_project_deadline_project_progress_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='construction_type',
            field=models.CharField(choices=[('commercial', 'Commercial'), ('residential', 'Residential'), ('industrial', 'Industrial'), ('infrastructure', 'Infrastructure')], default='commercial', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='subcontractors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'subcontractor'}, related_name='subcontracted_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
