# Generated by Django 6.0.3 on 2026-03-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_location_alter_project_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
