# Generated by Django 6.0.3 on 2026-03-23 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_address_line_2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='site_engineer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'site-engineer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineered_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
