# Generated by Django 6.0.3 on 2026-04-06 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_milestone_phasetask'),
    ]

    operations = [
        migrations.AddField(
            model_name='phasetask',
            name='completed_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phasetask',
            name='target_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phasetask',
            name='tracking_method',
            field=models.CharField(choices=[('manual', 'Manual Percentage'), ('subtasks', 'Subtasks Checkboxes'), ('units', 'Physical Units/Quantities')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='phasetask',
            name='unit_name',
            field=models.CharField(blank=True, help_text='e.g. Tons, Meters, Hours', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='phase_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_tasks', to='projects.phasetask'),
        ),
    ]
