# Generated by Django 6.0.3 on 2026-04-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_phasetask_completed_units_phasetask_target_units_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminded_due_soon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='reminded_overdue',
            field=models.BooleanField(default=False),
        ),
    ]
