# Generated by Django 6.0.3 on 2026-04-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_task_reminded_due_soon_task_reminded_overdue'),
    ]

    operations = [
        migrations.AddField(
            model_name='phasetask',
            name='duration_working_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='phasetask',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
