# Generated by Django 6.0.3 on 2026-04-26 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_phasetask_duration_working_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phasetask',
            name='depends_on',
            field=models.ForeignKey(blank=True, help_text='Task that must be completed before this one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_tasks', to='projects.phasetask'),
        ),
    ]
