# Generated by Django 6.0.3 on 2026-04-26 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_phasetask_depends_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='phasetask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='User assigned to execute this phase task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_phase_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
