# Generated by Django 6.0.3 on 2026-04-26 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_phasetask_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baselines', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='PhaseTaskBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duration_working_days', models.IntegerField(default=1)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('original_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baseline_records', to='projects.phasetask')),
                ('baseline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseline_tasks', to='projects.projectbaseline')),
            ],
        ),
    ]
