# Generated by Django 6.0.3 on 2026-04-26 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_projectbaseline_phasetaskbaseline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
    ]
