# Generated by Django 6.0.3 on 2026-04-26 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_remove_task_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phasetask',
            name='assigned_to',
        ),
    ]
