# Generated by Django 6.0.3 on 2026-04-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_phasetask_assigned_to_task_assigned_to'),
        ('workforce', '0003_worker_end_date_worker_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phasetask',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, help_text='Workers assigned to execute this phase task', related_name='assigned_phase_tasks', to='workforce.worker'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='workforce.worker'),
        ),
    ]
