# Generated by Django 6.0.2 on 2026-05-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_budgetcategory_subtask_required_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='required_role',
        ),
        migrations.RemoveField(
            model_name='task',
            name='required_role',
        ),
        migrations.AddField(
            model_name='subtask',
            name='required_skills',
            field=models.JSONField(blank=True, default=list, help_text='Skills required for auto-assignment'),
        ),
        migrations.AddField(
            model_name='task',
            name='required_skills',
            field=models.JSONField(blank=True, default=list, help_text='Skills required for auto-assignment'),
        ),
    ]
