# Generated by Django 6.0.2 on 2026-05-18 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_siteincident'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='procurement_officer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'procurement-officer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='site_accountant',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'site-accountant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_accounting_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='site_foreman',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'site-foreman'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foreman_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
