# Generated by Django 6.0.2 on 2026-05-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_project_status_is_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectphase',
            name='is_standard',
            field=models.BooleanField(default=False, help_text='True when created from the standard construction phase template.'),
        ),
    ]
