# Generated by Django migration

import uuid
from django.db import migrations, models


def assign_unique_tokens(apps, schema_editor):
    GeneratedReport = apps.get_model('projects', 'GeneratedReport')
    for report in GeneratedReport.objects.all():
        report.verification_token = uuid.uuid4()
        report.save(update_fields=['verification_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_alter_projectphase_is_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedreport',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(assign_unique_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='generatedreport',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
