# Generated by Django 6.0.2 on 2026-06-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_generatedreport_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedreport',
            name='report_type',
            field=models.CharField(choices=[('Progress', 'Monthly Progress Report'), ('Financial', 'Cost Variance Analysis'), ('HR', 'Resource Utilization'), ('Procurement', 'Material Inventory Log'), ('Timeline', 'Project Timeline Report'), ('Daily', 'Daily Transactions Report'), ('Custom', 'Custom Transactions Report'), ('Executive', 'Executive Summary Report')], max_length=50),
        ),
    ]
