import {
  FileText,
  Download,
  Calendar,
  Plus,
  PieChart as PieChartIcon,
  BarChart2,
  Table,
  FileSpreadsheet,
  X,
  TrendingUp,
  Briefcase,
} from "lucide-react";
import { useState, useEffect, useMemo } from "react";
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, PieChart, Pie, Cell, Legend } from "recharts";
import api from "../api";
import { useProject } from "../context/ProjectContext";
import { TableReportActions } from "../components/TableReportActions";
import type { TableReportData } from "../utils/tableReportExport";

export function Reports() {
  const [isProjectSelectOpen, setIsProjectSelectOpen] = useState(false);
  const [projects, setProjects] = useState<any[]>([]);
  const [selectedReportType, setSelectedReportType] = useState<string | null>(null);
  const [recentReports, setRecentReports] = useState<any[]>([]);
  const [analyticsData, setAnalyticsData] = useState<any>(null);
  const { currentProjectId } = useProject();

  const fetchRecentReports = async () => {
    try {
      const url = currentProjectId ? `/projects/generated-reports/?project=${currentProjectId}` : '/projects/generated-reports/';
      const response = await api.get(url);
      setRecentReports(response.data);
    } catch (error) {
      console.error('Error fetching recent reports', error);
    }
  };

  const fetchAnalytics = async () => {
    try {
      const url = currentProjectId ? `/projects/portfolio-analytics/?project=${currentProjectId}` : '/projects/portfolio-analytics/';
      const response = await api.get(url);
      setAnalyticsData(response.data);
    } catch (error) {
      console.error('Error fetching portfolio analytics', error);
    }
  };

  useEffect(() => {
    const fetchProjects = async () => {
      try {
        const response = await api.get('/projects/');
        setProjects(response.data);
      } catch (error) {
        console.error('Error fetching projects', error);
      }
    };
    fetchProjects();
    fetchRecentReports();
    fetchAnalytics();
  }, [currentProjectId]);

  const handleExportReport = async (projectId: number) => {
    if (!selectedReportType) return;
    try {
      const response = await api.get(`projects/${projectId}/generate-report/?type=${selectedReportType}`, { responseType: 'blob' });
      const file = new Blob([response.data], { type: 'application/pdf' });
      const fileURL = URL.createObjectURL(file);
      window.open(fileURL, '_blank');
      setIsProjectSelectOpen(false);
      fetchRecentReports(); // Refresh recent reports
    } catch (error) {
      console.error('Error downloading report', error);
      alert('Failed to generate report.');
    }
  };

  const templates = [
    {
      name: "Monthly Progress Report",
      type: "Progress",
      icon: BarChart2,
      color: "bg-blue-100 text-blue-600",
    },
    {
      name: "Cost Variance Analysis",
      type: "Financial",
      icon: PieChartIcon,
      color: "bg-green-100 text-green-600",
    },
    {
      name: "Resource Utilization",
      type: "HR",
      icon: Table,
      color: "bg-purple-100 text-purple-600",
    },
    {
      name: "Material Inventory Log",
      type: "Procurement",
      icon: FileSpreadsheet,
      color: "bg-orange-100 text-orange-600",
    },
  ];

  const recentReportsTable = useMemo((): TableReportData => {
    const columns = ["Report name", "Project", "Date generated", "Generated by", "Size (KB)"];
    const rows = recentReports.map((report) => [
      report.name,
      report.project_name ?? "—",
      new Date(report.created_at).toLocaleString(),
      report.created_by_name ?? "—",
      (report.file_size_bytes / 1024).toFixed(1),
    ]);
    return {
      title: "Recent Generated Reports",
      subtitle: `${recentReports.length} reports`,
      filename: "Recent_Reports",
      columns,
      rows,
    };
  }, [recentReports]);

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-slate-900 mb-2">
            Reporting & Analytics
          </h1>
          <p className="text-slate-600">
            Generate, schedule, and export project reports
          </p>
        </div>
        <button className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors">
          <Plus size={18} />
          <span className="text-sm font-medium">Create Custom Report</span>
        </button>
      </div>

      {/* PERFORMANCE ANALYTICS SECTION */}
      {analyticsData && (
        <div className="space-y-6 mb-8">
          {/* KPIs */}
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <div className="bg-white p-5 rounded-lg border border-slate-200 shadow-sm flex items-center justify-between">
              <div>
                <p className="text-sm text-slate-500 font-medium">Total Projects</p>
                <p className="text-2xl font-bold text-slate-900">{analyticsData.kpis.total_projects}</p>
              </div>
              <div className="p-3 bg-blue-50 text-blue-600 rounded-lg"><Briefcase size={24} /></div>
            </div>
            <div className="bg-white p-5 rounded-lg border border-slate-200 shadow-sm flex items-center justify-between">
              <div>
                <p className="text-sm text-slate-500 font-medium">Total Budget</p>
                <p className="text-2xl font-bold text-slate-900">Rwf {(analyticsData.kpis.total_budget / 1000000).toFixed(1)}M</p>
              </div>
              <div className="p-3 bg-green-50 text-green-600 rounded-lg"><PieChart size={24} /></div>
            </div>
            <div className="bg-white p-5 rounded-lg border border-slate-200 shadow-sm flex items-center justify-between">
              <div>
                <p className="text-sm text-slate-500 font-medium">Actual Spend</p>
                <p className="text-2xl font-bold text-slate-900">Rwf {(analyticsData.kpis.total_spend / 1000000).toFixed(1)}M</p>
              </div>
              <div className="p-3 bg-red-50 text-red-600 rounded-lg"><TrendingUp size={24} /></div>
            </div>
            <div className="bg-white p-5 rounded-lg border border-slate-200 shadow-sm flex items-center justify-between">
              <div>
                <p className="text-sm text-slate-500 font-medium">Avg Progress</p>
                <p className="text-2xl font-bold text-slate-900">{analyticsData.kpis.avg_progress.toFixed(1)}%</p>
              </div>
              <div className="p-3 bg-purple-50 text-purple-600 rounded-lg"><BarChart2 size={24} /></div>
            </div>
          </div>

          {/* CHARTS */}
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            <div className="lg:col-span-2 bg-white p-6 rounded-lg border border-slate-200 shadow-sm">
              <h2 className="text-lg font-bold text-slate-900 mb-4">Financial Cash Flow (Spend)</h2>
              <div className="h-72">
                <ResponsiveContainer width="100%" height="100%">
                  <LineChart data={analyticsData.cash_flow}>
                    <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0" />
                    <XAxis dataKey="date" stroke="#94a3b8" fontSize={12} tickLine={false} axisLine={false} />
                    <YAxis 
                      stroke="#94a3b8" 
                      fontSize={12} 
                      tickLine={false} 
                      axisLine={false}
                      tickFormatter={(value) => `Rwf ${(value / 1000000).toFixed(1)}M`}
                    />
                    <Tooltip 
                      formatter={(value: any) => [`Rwf ${value.toLocaleString()}`, "Spend"]}
                      contentStyle={{ borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }}
                    />
                    <Line type="monotone" dataKey="amount" stroke="#3b82f6" strokeWidth={3} dot={{ r: 4, fill: "#3b82f6", strokeWidth: 2, stroke: "#fff" }} activeDot={{ r: 6 }} />
                  </LineChart>
                </ResponsiveContainer>
              </div>
            </div>

            <div className="bg-white p-6 rounded-lg border border-slate-200 shadow-sm">
              <h2 className="text-lg font-bold text-slate-900 mb-4">Project Status Distribution</h2>
              <div className="h-72">
                <ResponsiveContainer width="100%" height="100%">
                  <PieChart>
                    <Pie
                      data={analyticsData.status_distribution}
                      cx="50%"
                      cy="45%"
                      innerRadius={60}
                      outerRadius={80}
                      paddingAngle={5}
                      dataKey="value"
                    >
                      {analyticsData.status_distribution.map((entry: any, index: number) => {
                        const COLORS: Record<string, string> = {
                          'on-track': '#22c55e',
                          'at-risk': '#f59e0b',
                          'delayed': '#ef4444',
                          'completed': '#3b82f6'
                        };
                        return <Cell key={`cell-${index}`} fill={COLORS[entry.name] || '#cbd5e1'} />;
                      })}
                    </Pie>
                    <Tooltip 
                      formatter={(value: any, name: any, props: any) => [value, props.payload.name.replace('-', ' ').toUpperCase()]}
                      contentStyle={{ borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }}
                    />
                    <Legend 
                      verticalAlign="bottom" 
                      height={36}
                      formatter={(value) => <span className="text-sm text-slate-600 capitalize">{value.replace('-', ' ')}</span>}
                    />
                  </PieChart>
                </ResponsiveContainer>
              </div>
            </div>
          </div>
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 space-y-6">
          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-4">
              Report Templates
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {templates.map((template, index) => (
                <div
                  key={index}
                  className="bg-white p-5 rounded-lg border border-slate-200 hover:border-blue-300 hover:shadow-md transition-all cursor-pointer group"
                >
                  <div className="flex items-start justify-between mb-4">
                    <div className={`p-3 rounded-lg ${template.color}`}>
                      <template.icon size={24} />
                    </div>
                    <span className="text-xs font-medium text-slate-500 bg-slate-100 px-2 py-1 rounded">
                      {template.type}
                    </span>
                  </div>
                  <h3 className="font-bold text-slate-900 mb-1 group-hover:text-blue-600 transition-colors">
                    {template.name}
                  </h3>
                  <p className="text-sm text-slate-500 mb-4">
                    Standard template for {template.name.toLowerCase()} with key
                    metrics.
                  </p>
                  <div className="flex gap-2">
                    <button 
                      onClick={() => {
                        setSelectedReportType(template.type);
                        setIsProjectSelectOpen(true);
                      }}
                      className="flex-1 py-2 text-sm font-medium text-blue-600 bg-blue-50 rounded hover:bg-blue-100 transition-colors"
                    >
                      Generate
                    </button>
                    <button className="px-3 py-2 text-slate-400 hover:text-slate-600 bg-slate-50 rounded hover:bg-slate-100 transition-colors">
                      <Calendar size={18} />
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </section>

          <section className="bg-white rounded-lg border border-slate-200 p-6">
            <div className="flex flex-wrap items-center justify-between gap-3 mb-6">
              <h2 className="text-xl font-bold text-slate-900">
                Recent Reports
              </h2>
              <div className="flex flex-wrap items-center gap-3">
                <TableReportActions
                  report={recentReportsTable}
                  projectId={currentProjectId ?? undefined}
                  disabled={recentReports.length === 0}
                />
                <button className="text-sm text-blue-600 hover:text-blue-700 font-medium">
                  View Archive
                </button>
              </div>
            </div>
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead>
                  <tr className="border-b border-slate-200">
                    <th className="text-left py-3 px-4 text-sm font-semibold text-slate-700">
                      Report Name
                    </th>
                    <th className="text-left py-3 px-4 text-sm font-semibold text-slate-700">
                      Date Generated
                    </th>
                    <th className="text-left py-3 px-4 text-sm font-semibold text-slate-700">
                      Generated By
                    </th>
                    <th className="text-right py-3 px-4 text-sm font-semibold text-slate-700">
                      Actions
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {recentReports.length > 0 ? recentReports.map((report, index) => (
                    <tr
                      key={index}
                      className="border-b border-slate-100 hover:bg-slate-50"
                    >
                      <td className="py-3 px-4">
                        <div className="flex items-center gap-3">
                          <div className="p-2 bg-slate-100 rounded text-slate-500">
                            <FileText size={16} />
                          </div>
                          <div>
                            <p className="text-sm font-medium text-slate-900">
                              {report.name}
                            </p>
                            <p className="text-xs text-slate-500">
                              PDF • {(report.file_size_bytes / 1024).toFixed(1)} KB • {report.project_name}
                            </p>
                          </div>
                        </div>
                      </td>
                      <td className="py-3 px-4 text-sm text-slate-600">
                        {new Date(report.created_at).toLocaleDateString()}
                      </td>
                      <td className="py-3 px-4 text-sm text-slate-600">
                        {report.created_by_name}
                      </td>
                      <td className="py-3 px-4 text-right">
                        <a href={report.file} target="_blank" rel="noopener noreferrer" className="text-slate-400 hover:text-blue-600 transition-colors inline-block">
                          <Download size={18} />
                        </a>
                      </td>
                    </tr>
                  )) : (
                    <tr>
                      <td colSpan={4} className="py-8 text-center text-slate-500 text-sm">
                        No reports generated yet.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </section>
        </div>

        <div className="space-y-6">
          <div className="bg-white rounded-lg border border-slate-200 p-6">
            <h2 className="text-lg font-bold text-slate-900 mb-4">
              Scheduled Reports
            </h2>
            <div className="space-y-4">
              {[
                {
                  name: "Weekly Progress Update",
                  schedule: "Every Monday, 9:00 AM",
                  recipients: 8,
                },
                {
                  name: "Monthly Financials",
                  schedule: "1st of month, 10:00 AM",
                  recipients: 4,
                },
                {
                  name: "Daily Site Log",
                  schedule: "Daily, 6:00 PM",
                  recipients: 3,
                },
              ].map((item, idx) => (
                <div
                  key={idx}
                  className="flex items-start gap-3 p-3 bg-slate-50 rounded-lg border border-slate-100"
                >
                  <Calendar className="text-blue-600 shrink-0 mt-1" size={18} />
                  <div>
                    <h3 className="text-sm font-semibold text-slate-900">
                      {item.name}
                    </h3>
                    <p className="text-xs text-slate-500">{item.schedule}</p>
                    <p className="text-xs text-slate-500 mt-1">
                      {item.recipients} recipients
                    </p>
                  </div>
                </div>
              ))}
            </div>
            <button className="w-full mt-4 py-2 text-sm font-medium text-blue-600 border border-blue-200 rounded-lg hover:bg-blue-50 transition-colors">
              Manage Schedules
            </button>
          </div>


        </div>
      </div>

      {/* Project Selection Modal */}
      {isProjectSelectOpen && (
        <div className="fixed inset-0 bg-slate-900/50 backdrop-blur-sm flex items-center justify-center z-[100] p-4">
          <div className="bg-white rounded-xl shadow-2xl w-full max-w-md overflow-hidden animate-fade-in">
            <div className="flex items-center justify-between p-6 border-b border-slate-100">
              <h2 className="text-xl font-bold text-slate-900">Select Project</h2>
              <button 
                onClick={() => setIsProjectSelectOpen(false)}
                className="text-slate-400 hover:text-slate-600 p-1 rounded-lg hover:bg-slate-100 transition-colors"
              >
                <X size={20} />
              </button>
            </div>
            
            <div className="p-6 max-h-[400px] overflow-y-auto">
              <p className="text-sm text-slate-500 mb-4">Choose a project to generate a financial status report for:</p>
              
              {projects.length > 0 ? (
                <div className="space-y-3">
                  {projects.map((project) => (
                    <button
                      key={project.id}
                      onClick={() => handleExportReport(project.id)}
                      className="w-full text-left p-4 rounded-xl border border-slate-200 hover:border-blue-300 hover:shadow-md transition-all group"
                    >
                      <h3 className="font-semibold text-slate-900 group-hover:text-blue-600">{project.name}</h3>
                      <p className="text-sm text-slate-500 mt-1">Status: {project.status}</p>
                    </button>
                  ))}
                </div>
              ) : (
                <p className="text-center text-slate-500 py-4">No projects available.</p>
              )}
            </div>
            
            <div className="p-6 border-t border-slate-100 bg-slate-50 flex justify-end">
              <button 
                onClick={() => setIsProjectSelectOpen(false)}
                className="px-4 py-2 font-medium text-slate-600 hover:text-slate-900 transition-colors"
              >
                Cancel
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
