# Generated by Django 6.0.3 on 2026-04-12 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0008_phasetask_completed_units_phasetask_target_units_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(choices=[('mason', 'Mason'), ('carpenter', 'Carpenter'), ('plumber', 'Plumber'), ('electrician', 'Electrician'), ('laborer', 'Laborer'), ('welder', 'Welder'), ('painter', 'Painter'), ('driver', 'Driver'), ('other', 'Other')], max_length=50)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half-day', 'Half-Day'), ('leave', 'Leave')], default='present', max_length=20)),
                ('overtime_hours', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='workforce.worker')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('worker', 'date')},
            },
        ),
    ]
