# Generated by Django 6.0.3 on 2026-04-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0002_dailypayroll_payrollrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
