# Generated by Django 6.0.3 on 2026-03-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_material_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='materials_supplied',
            field=models.ManyToManyField(blank=True, related_name='suppliers', to='procurement.material'),
        ),
    ]
