# Generated by Django 6.0.2 on 2026-05-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_purchaseorder_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='order_type',
            field=models.CharField(choices=[('material', 'Material'), ('equipment', 'Equipment')], default='material', max_length=20),
        ),
    ]
