# Generated by Django 6.0.2 on 2026-05-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_purchaseorder_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('on-track', 'On Track'), ('delayed', 'Delayed'), ('completed', 'Completed')], default='on-track', max_length=20),
        ),
    ]
