# Generated by Django 6.0.3 on 2026-04-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_systemlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'System Admin'), ('project-manager', 'Project Manager'), ('site-engineer', 'Site Engineer'), ('subcontractor', 'Subcontractor'), ('procurement-officer', 'Procurement Officer'), ('safety-officer', 'Safety Officer'), ('accountant', 'Accountant'), ('client', 'Client')], default='site-engineer', max_length=50),
        ),
    ]
