# Generated by Django 6.0.2 on 2026-05-18 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('executive', 'Executive'), ('finance', 'Finance'), ('technical', 'Technical'), ('site', 'Site Operations'), ('external', 'External')], default='site', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'System Admin'), ('managing-director', 'Managing Director'), ('director-finance', 'Director of Finance'), ('technical-director', 'Technical Director'), ('accountant', 'Accountant'), ('project-manager', 'Project Manager'), ('procurement-officer', 'Procurement Officer'), ('site-accountant', 'Site Accountant'), ('site-engineer', 'Site Engineer'), ('site-foreman', 'Site Foreman'), ('subcontractor', 'Subcontractor'), ('safety-officer', 'Safety Officer'), ('client', 'Client')], default='site-engineer', max_length=50),
        ),
    ]
