"""Shared metadata, QR verification, and footer blocks for BuildWise PDF reports."""

import io
import uuid
from datetime import datetime

from django.conf import settings
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.utils import ImageReader
from reportlab.platypus import Image as RLImage, Paragraph, Spacer, Table, TableStyle


def new_verification_token():
    return uuid.uuid4()


def get_exporter_name(user) -> str:
    if not user:
        return "BuildWise System"
    name = (
        getattr(user, 'full_name', None)
        or f"{getattr(user, 'first_name', '')} {getattr(user, 'last_name', '')}".strip()
        or getattr(user, 'username', None)
        or "Unknown User"
    )
    role = getattr(user, 'get_role_display', lambda: None)()
    if role:
        return f"{name} ({role})"
    return name


def format_report_datetime(dt=None) -> str:
    dt = dt or datetime.now()
    return dt.strftime("%B %d, %Y at %I:%M %p")


def resolve_public_api_base(request=None) -> str:
    """
    Base URL embedded in report QR codes for verification links.
    Uses PUBLIC_API_BASE from settings (default http://127.0.0.1:8000).
    """
    configured = (getattr(settings, 'PUBLIC_API_BASE', None) or '').strip().rstrip('/')
    if configured:
        return configured

    port = getattr(settings, 'API_PORT', '8000')
    if request is not None:
        host_header = request.get_host()
        scheme = 'https' if request.is_secure() else 'http'
        return f'{scheme}://{host_header}'.rstrip('/')

    return f'http://127.0.0.1:{port}'


def build_verification_url(token, request=None) -> str:
    base = resolve_public_api_base(request)
    return f'{base}/api/projects/generated-reports/verify/{token}/'


def _qr_image_bytes(verification_url: str) -> io.BytesIO:
    import qrcode

    qr = qrcode.QRCode(version=1, box_size=4, border=2)
    qr.add_data(verification_url)
    qr.make(fit=True)
    img = qr.make_image(fill_color="#0f172a", back_color="white")
    buf = io.BytesIO()
    img.save(buf, format='PNG')
    buf.seek(0)
    return buf


def qr_flowable(verification_url: str, size: float = 72):
    buf = _qr_image_bytes(verification_url)
    return RLImage(buf, width=size, height=size)


def build_header_project_info_html(project, *, exported_by=None, extra_lines=None):
    lines = [
        f"<b>Project:</b> {project.name}",
        f"<b>Generated:</b> {format_report_datetime()}",
        f"<b>Exported by:</b> {get_exporter_name(exported_by)}",
    ]
    if extra_lines:
        lines.extend(extra_lines)
    return "<br/>".join(lines)


def header_project_info_style():
    return ParagraphStyle(
        'ProjInfo',
        fontName='Helvetica',
        fontSize=10,
        textColor=colors.whitesmoke,
        alignment=TA_RIGHT,
        leading=13,
    )


def append_report_footer(elements, styles, *, exported_by=None, verification_token=None, verify_url=None):
    """Standard footer: exporter, timestamp, optional QR for validation."""
    normal = styles['Normal']
    footer_style = ParagraphStyle(
        'ReportFooter',
        parent=normal,
        fontName='Helvetica',
        fontSize=8,
        textColor=colors.HexColor("#64748b"),
        alignment=TA_CENTER,
        leading=11,
    )
    meta_style = ParagraphStyle(
        'ReportFooterMeta',
        parent=normal,
        fontName='Helvetica',
        fontSize=9,
        textColor=colors.HexColor("#334155"),
        alignment=TA_LEFT,
        leading=13,
    )

    elements.append(Spacer(1, 20))

    meta_lines = [
        f"<b>Exported by:</b> {get_exporter_name(exported_by)}",
        f"<b>Generated:</b> {format_report_datetime()}",
    ]
    if verification_token and verify_url:
        meta_lines.append(
            "<b>Validation:</b> Scan the QR code to view and verify this report online."
        )
        qr = qr_flowable(verify_url)
        meta = Paragraph("<br/>".join(meta_lines), meta_style)
        footer_row = Table([[qr, meta]], colWidths=[82, 448])
        footer_row.setStyle(TableStyle([
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('LEFTPADDING', (0, 0), (-1, -1), 0),
            ('RIGHTPADDING', (0, 0), (-1, -1), 0),
            ('TOPPADDING', (0, 0), (-1, -1), 4),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ]))
        elements.append(footer_row)
    else:
        elements.append(Paragraph("<br/>".join(meta_lines), meta_style))

    elements.append(Spacer(1, 8))
    elements.append(Paragraph(
        "Automatically generated by the BuildWise Project Control Suite.",
        footer_style,
    ))
    elements.append(Paragraph(
        "Confidential — for authorized project stakeholders only.",
        footer_style,
    ))


def draw_canvas_report_stamp(canvas, width, *, exported_by=None, verification_token=None, verify_url=None, y=52):
    """Metadata + QR block for canvas-based PDFs (PO, payment proof)."""
    canvas.saveState()
    canvas.setStrokeColor(colors.HexColor("#e2e8f0"))
    canvas.setLineWidth(0.5)
    canvas.line(50, y + 38, width - 50, y + 38)

    text_x = 50
    if verification_token and verify_url:
        buf = _qr_image_bytes(verify_url)
        canvas.drawImage(ImageReader(buf), width - 50 - 56, y - 4, width=56, height=56, mask='auto')
        text_x = 50

    canvas.setFillColor(colors.HexColor("#64748b"))
    canvas.setFont("Helvetica", 8)
    canvas.drawString(text_x, y + 22, f"Exported by: {get_exporter_name(exported_by)}")
    canvas.drawString(text_x, y + 10, f"Generated: {format_report_datetime()}")
    if verification_token and verify_url:
        canvas.drawString(text_x, y - 2, "Scan QR code to verify this document online.")
    canvas.restoreState()
